// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
)

func main() {
	h := server.New(server.WithHostPorts("0.0.0.0:8080"),
		server.WithHandleMethodNotAllowed(true),
	)

	h.Use(cors.New(cors.Config{
		AllowOrigins: []string{
			"*"},
		AllowMethods: []string{
			"PUT", "PATCH", "POST", "GET", "DELETE"},
		AllowHeaders: []string{
			"Origin", "Authorization", "Content-Type"},
		ExposeHeaders: []string{
			"Content-Type"},
		AllowCredentials: true,
		AllowOriginFunc: func(origin string) bool {
			return true
		},
		MaxAge: 24 * time.Hour,
	}))
	register(h)
	h.Spin()
}
