// Code generated by hertz generator.

package typo

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gittypomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
